name: brl_task_4
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.4.0
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.12.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  location: ^8.0.1
  lottie: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/District_icon.png"

flutter:
  assets:
    - assets/images/
    - assets/movieimg/movies/
    - assets/movieimg/
  uses-material-design: true
