final List<Map<String, dynamic>> sampleMovies = [
  {
    'id': 'movie_001',
    'title': 'Kantara: A Legend Chapter-1',
    'bannerImage': 'assets/movieimg/movies/kantara.jpeg',
    'certificate': 'UA/16+',
    'language': 'Kannada',
    'duration': '2 hr 49 min',
    'releaseDate': '14 March 2025',
    'genres': ['Adventure', 'Drama', 'Thriller'],
    'synopsis':
        'Exploring the origins of Kand-bhatta Shiva during the Kadamba dynasty era, delving into the untamed wilderness and forgotten lore surrounding his past.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '28', 'day': 'Mon'},
      {'date': '29', 'day': 'Tue'},
      {'date': '30', 'day': 'Wed'},
      {'date': '31', 'day': 'Thu'},
    ],
    'offers': ['Flat ₹75 cashback on Paytm Movie Tickets'],
  },
  {
    'id': 'movie_002',
    'title': 'Deadpool & Wolverine',
    'bannerImage': 'assets/movieimg/movies/deadpool.jpg',
    'certificate': 'A',
    'language': 'English',
    'duration': '2 hr 20 min',
    'releaseDate': 'July 2024',
    'genres': ['Action', 'Comedy'],
    'synopsis':
        'Deadpool teams up with Wolverine for a chaotic multiverse adventure filled with humor and fourth-wall-breaking madness.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '28', 'day': 'Mon'},
      {'date': '29', 'day': 'Tue'},
      {'date': '30', 'day': 'Wed'},
      {'date': '31', 'day': 'Thu'},
    ],
    'offers': ['Get 10% off with SBI Credit Card'],
  },
  {
    'id': 'movie_003',
    'title': 'Inside Out 2',
    'bannerImage': 'assets/movieimg/movies/inside.jpeg',
    'certificate': 'U',
    'language': 'English',
    'duration': '1 hr 50 min',
    'releaseDate': 'June 2024',
    'genres': ['Animation', 'Family', 'Comedy'],
    'synopsis':
        'Riley experiences new emotions as she navigates the challenges of teenage life, with Joy and the gang back in action.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '28', 'day': 'Mon'},
      {'date': '29', 'day': 'Tue'},
      {'date': '30', 'day': 'Wed'},
      {'date': '31', 'day': 'Thu'},
    ],
    'offers': ['Buy 2 tickets and get popcorn free!'],
  },
  {
    'id': 'movie_004',
    'title': 'Oppenheimer',
    'bannerImage': 'assets/movieimg/movies/oppenheimer.jpg',
    'certificate': 'UA/16+',
    'language': 'English',
    'duration': '3 hr',
    'releaseDate': 'July 2023',
    'genres': ['Biography', 'Drama', 'History'],
    'synopsis':
        'The story of J. Robert Oppenheimer, the man behind the atomic bomb, and the consequences of his genius.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '28', 'day': 'Mon'},
      {'date': '29', 'day': 'Tue'},
      {'date': '30', 'day': 'Wed'},
      {'date': '31', 'day': 'Thu'},
    ],
    'offers': ['50% off on weekday morning shows!'],
  },
  {
    'id': 'movie_005',
    'title': 'Pushpa 2: The Rule',
    'bannerImage': 'assets/movieimg/movies/pushpa.jpg',
    'certificate': 'UA',
    'language': 'Telugu',
    'duration': '2 hr 45 min',
    'releaseDate': 'August 2024',
    'genres': ['Action', 'Drama'],
    'synopsis':
        'Pushpa returns stronger than ever, battling both his enemies and the system in a fight for dominance and survival.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '28', 'day': 'Mon'},
      {'date': '29', 'day': 'Tue'},
      {'date': '30', 'day': 'Wed'},
      {'date': '31', 'day': 'Thu'},
    ],
    'offers': ['Exclusive early screening offers for fans!'],
  },
  {
    'id': 'movie_006',
    'title': 'Kalki 2898 AD',
    'bannerImage': 'assets/movieimg/movies/kalki.jpg',
    'certificate': 'UA/13+',
    'language': 'Telugu',
    'duration': '3 hr 2 min',
    'releaseDate': 'June 2024',
    'genres': ['Sci-Fi', 'Action', 'Fantasy'],
    'synopsis':
        'In a dystopian future, the world awaits the arrival of Kalki — the final avatar who will restore balance to humanity.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '1', 'day': 'Fri'},
      {'date': '2', 'day': 'Sat'},
      {'date': '3', 'day': 'Sun'},
      {'date': '4', 'day': 'Mon'},
    ],
    'offers': ['Flat 20% off for first 100 bookings!'],
  },
  {
    'id': 'movie_007',
    'title': 'Joker: Folie à Deux',
    'bannerImage': 'assets/movieimg/movies/joker.jpg',
    'certificate': 'A',
    'language': 'English',
    'duration': '2 hr 15 min',
    'releaseDate': 'October 2024',
    'genres': ['Crime', 'Drama', 'Musical'],
    'synopsis':
        'Arthur Fleck returns, joined by Harley Quinn, as they navigate madness, fame, and chaos in Gotham City.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '10', 'day': 'Fri'},
      {'date': '11', 'day': 'Sat'},
      {'date': '12', 'day': 'Sun'},
      {'date': '13', 'day': 'Mon'},
    ],
    'offers': ['Buy 1 Get 1 Free on premiere day!'],
  },
  {
    'id': 'movie_008',
    'title': 'Dune: Part Two',
    'bannerImage': 'assets/movieimg/movies/dune.jpg',
    'certificate': 'UA/13+',
    'language': 'English',
    'duration': '2 hr 46 min',
    'releaseDate': 'March 2024',
    'genres': ['Sci-Fi', 'Adventure', 'Drama'],
    'synopsis':
        'Paul Atreides unites with the Fremen and plots revenge against the conspirators who destroyed his family.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '5', 'day': 'Wed'},
      {'date': '6', 'day': 'Thu'},
      {'date': '7', 'day': 'Fri'},
      {'date': '8', 'day': 'Sat'},
    ],
    'offers': ['Special IMAX screening discounts!'],
  },
  {
    'id': 'movie_009',
    'title': 'Leo',
    'bannerImage': 'assets/movieimg/movies/leo.jpg',
    'certificate': 'UA',
    'language': 'Tamil',
    'duration': '2 hr 45 min',
    'releaseDate': 'October 2023',
    'genres': ['Action', 'Thriller'],
    'synopsis':
        'A peaceful man is drawn back into his violent past, blurring the lines between savior and killer.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '12', 'day': 'Thu'},
      {'date': '13', 'day': 'Fri'},
      {'date': '14', 'day': 'Sat'},
      {'date': '15', 'day': 'Sun'},
    ],
    'offers': ['20% off on student tickets!'],
  },
  {
    'id': 'movie_010',
    'title': 'Spider-Man: Beyond the Spider-Verse',
    'bannerImage': 'assets/movieimg/movies/spider.jpeg',
    'certificate': 'U/A',
    'language': 'English',
    'duration': '2 hr 10 min',
    'releaseDate': 'December 2025',
    'genres': ['Animation', 'Action', 'Adventure'],
    'synopsis':
        'Miles Morales teams up with new Spider-People across dimensions in the next chapter of the Spider-Verse saga.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '15', 'day': 'Fri'},
      {'date': '16', 'day': 'Sat'},
      {'date': '17', 'day': 'Sun'},
      {'date': '18', 'day': 'Mon'},
    ],
    'offers': ['Flat ₹100 off on Fandango app!'],
  },
    {
    'id': 'movie_011',
    'title': 'The Batman 2',
    'bannerImage': 'assets/movieimg/movies/batman.jpeg',
    'certificate': 'UA',
    'language': 'English',
    'duration': '2 hr 55 min',
    'releaseDate': 'June 2025',
    'genres': ['Action', 'Crime', 'Thriller'],
    'synopsis':
        'Bruce Wayne returns to face a new wave of chaos in Gotham as old enemies and new threats collide.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '19', 'day': 'Tue'},
      {'date': '20', 'day': 'Wed'},
      {'date': '21', 'day': 'Thu'},
      {'date': '22', 'day': 'Fri'},
    ],
    'offers': ['Buy 3 get 1 ticket free!'],
  },
  {
    'id': 'movie_012',
    'title': 'Avatar: The Seed Bearer',
    'bannerImage': 'assets/movieimg/movies/avatar.jpg',
    'certificate': 'U/A',
    'language': 'English',
    'duration': '3 hr 5 min',
    'releaseDate': 'December 2025',
    'genres': ['Sci-Fi', 'Adventure', 'Fantasy'],
    'synopsis':
        'Jake Sully and Neytiri embark on a new journey to protect their home from human invaders once again.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '8', 'day': 'Mon'},
      {'date': '9', 'day': 'Tue'},
      {'date': '10', 'day': 'Wed'},
      {'date': '11', 'day': 'Thu'},
    ],
    'offers': ['Free popcorn on IMAX show bookings!'],
  },
  {
    'id': 'movie_013',
    'title': 'Mission Impossible: Dead Reckoning Part Two',
    'bannerImage': 'assets/movieimg/movies/mission.jpeg',
    'certificate': 'UA',
    'language': 'English',
    'duration': '2 hr 40 min',
    'releaseDate': 'November 2025',
    'genres': ['Action', 'Thriller'],
    'synopsis':
        'Ethan Hunt races against time to stop a rogue AI from controlling the world’s most dangerous secrets.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '3', 'day': 'Fri'},
      {'date': '4', 'day': 'Sat'},
      {'date': '5', 'day': 'Sun'},
      {'date': '6', 'day': 'Mon'},
    ],
    'offers': ['Get ₹150 off using Amazon Pay!'],
  },
  {
    'id': 'movie_014',
    'title': 'The Flash: Speed Force',
    'bannerImage': 'assets/movieimg/movies/flash.jpg',
    'certificate': 'U/A',
    'language': 'English',
    'duration': '2 hr 18 min',
    'releaseDate': 'May 2025',
    'genres': ['Action', 'Superhero', 'Adventure'],
    'synopsis':
        'Barry Allen must race against time itself to restore balance after a catastrophic timeline fracture.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '22', 'day': 'Sat'},
      {'date': '23', 'day': 'Sun'},
      {'date': '24', 'day': 'Mon'},
      {'date': '25', 'day': 'Tue'},
    ],
    'offers': ['Flat ₹50 off on early bird shows!'],
  },
  {
    'id': 'movie_015',
    'title': 'John Wick: Chapter 5',
    'bannerImage': 'assets/movieimg/movies/john.jpg',
    'certificate': 'A',
    'language': 'English',
    'duration': '2 hr 35 min',
    'releaseDate': 'March 2026',
    'genres': ['Action', 'Thriller', 'Crime'],
    'synopsis':
        'John Wick returns from the shadows for one final showdown against the global assassin order.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '14', 'day': 'Thu'},
      {'date': '15', 'day': 'Fri'},
      {'date': '16', 'day': 'Sat'},
      {'date': '17', 'day': 'Sun'},
    ],
    'offers': ['Exclusive merchandise for first 200 viewers!'],
  },
  {
    'id': 'movie_016',
    'title': 'Doctor Strange: The Multiverse Wars',
    'bannerImage': 'hassets/movieimg/movies/doctor.jpeg',
    'certificate': 'UA/13+',
    'language': 'English',
    'duration': '2 hr 35 min',
    'releaseDate': 'April 2026',
    'genres': ['Action', 'Fantasy', 'Sci-Fi'],
    'synopsis':
        'Doctor Strange faces his greatest challenge yet as universes collide in an all-out magical war.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '9', 'day': 'Fri'},
      {'date': '10', 'day': 'Sat'},
      {'date': '11', 'day': 'Sun'},
      {'date': '12', 'day': 'Mon'},
    ],
    'offers': ['Free Doctor Strange poster with IMAX tickets!'],
  },
  {
    'id': 'movie_017',
    'title': 'Avengers: Secret Wars',
    'bannerImage': 'assets/movieimg/movies/avenger.jpg',
    'certificate': 'UA/13+',
    'language': 'English',
    'duration': '3 hr 10 min',
    'releaseDate': 'May 2026',
    'genres': ['Action', 'Superhero', 'Adventure'],
    'synopsis':
        'The multiverse is collapsing, and the Avengers must unite across realities for the final stand.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '28', 'day': 'Wed'},
      {'date': '29', 'day': 'Thu'},
      {'date': '30', 'day': 'Fri'},
      {'date': '31', 'day': 'Sat'},
    ],
    'offers': ['Pre-book now and win exclusive Marvel goodies!'],
  },
  {
    'id': 'movie_018',
    'title': 'K.G.F: Chapter 3',
    'bannerImage': 'assets/movieimg/movies/KGF.jpg',
    'certificate': 'UA',
    'language': 'Kannada',
    'duration': '2 hr 55 min',
    'releaseDate': 'October 2025',
    'genres': ['Action', 'Drama', 'Crime'],
    'synopsis':
        'Rocky Bhai returns to rule the underworld, but new enemies rise to challenge his empire.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '7', 'day': 'Tue'},
      {'date': '8', 'day': 'Wed'},
      {'date': '9', 'day': 'Thu'},
      {'date': '10', 'day': 'Fri'},
    ],
    'offers': ['Early bird tickets at ₹99 only!'],
  },
  {
    'id': 'movie_019',
    'title': 'Salaar: Part 2 – Shouryaanga Parvam',
    'bannerImage': 'assets/movieimg/movies/salaar.jpg',
    'certificate': 'UA',
    'language': 'Telugu',
    'duration': '2 hr 50 min',
    'releaseDate': 'September 2025',
    'genres': ['Action', 'Drama'],
    'synopsis':
        'Deva returns to fulfill his destiny as a war between kingdoms erupts in the world of Khansaar.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '18', 'day': 'Thu'},
      {'date': '19', 'day': 'Fri'},
      {'date': '20', 'day': 'Sat'},
      {'date': '21', 'day': 'Sun'},
    ],
    'offers': ['Book now to get exclusive wallpapers!'],
  },
  {
    'id': 'movie_020',
    'title': 'The Lion King: Reborn',
    'bannerImage': 'assets/movieimg/movies/lion.jpg',
    'certificate': 'U',
    'language': 'English',
    'duration': '2 hr 5 min',
    'releaseDate': 'July 2026',
    'genres': ['Animation', 'Family', 'Drama'],
    'synopsis':
        'A new generation rises in the Pride Lands as Simba’s legacy continues in this reimagined saga.',
    'cast': [
      {'name': 'Actor 1', 'image': 'https://via.placeholder.com/100x100?text=Actor1'},
      {'name': 'Actor 2', 'image': 'https://via.placeholder.com/100x100?text=Actor2'},
    ],
    'availableDates': [
      {'date': '1', 'day': 'Wed'},
      {'date': '2', 'day': 'Thu'},
      {'date': '3', 'day': 'Fri'},
      {'date': '4', 'day': 'Sat'},
    ],
    'offers': ['Kids under 12 get 50% off!'],
  },
];
