// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDydsotYI3GEZJbdkY95EM228dk52V2zhE',
    appId: '1:409754702679:web:757dfbfe27c58f2caca412',
    messagingSenderId: '409754702679',
    projectId: 'district-app-7964d',
    authDomain: 'district-app-7964d.firebaseapp.com',
    storageBucket: 'district-app-7964d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGdUpHArikBORLSy38W1RjPnoyMmiH19g',
    appId: '1:409754702679:android:3e8f828197e2bc8aaca412',
    messagingSenderId: '409754702679',
    projectId: 'district-app-7964d',
    storageBucket: 'district-app-7964d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHL59h59JPMM7iYsBc9cBhgwx7NNQJsVA',
    appId: '1:409754702679:ios:a28af82236f503c8aca412',
    messagingSenderId: '409754702679',
    projectId: 'district-app-7964d',
    storageBucket: 'district-app-7964d.firebasestorage.app',
    iosBundleId: 'com.example.brlTask4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHL59h59JPMM7iYsBc9cBhgwx7NNQJsVA',
    appId: '1:409754702679:ios:a28af82236f503c8aca412',
    messagingSenderId: '409754702679',
    projectId: 'district-app-7964d',
    storageBucket: 'district-app-7964d.firebasestorage.app',
    iosBundleId: 'com.example.brlTask4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDydsotYI3GEZJbdkY95EM228dk52V2zhE',
    appId: '1:409754702679:web:bf328ca4fd0086ddaca412',
    messagingSenderId: '409754702679',
    projectId: 'district-app-7964d',
    authDomain: 'district-app-7964d.firebaseapp.com',
    storageBucket: 'district-app-7964d.firebasestorage.app',
  );
}
