// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3CFpHaRuD4kQ7Q02i0hWrFQSqwAB-aA',
    appId: '1:272011887725:web:bacd24fa001c9c0d56eb64',
    messagingSenderId: '272011887725',
    projectId: 'auth-district',
    authDomain: 'auth-district.firebaseapp.com',
    storageBucket: 'auth-district.firebasestorage.app',
    measurementId: 'G-XTTLWPDYVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1kP4eS7ekqcRLN7888NdlD2fwi8yWfnA',
    appId: '1:272011887725:android:e7403c7c9a23c68456eb64',
    messagingSenderId: '272011887725',
    projectId: 'auth-district',
    storageBucket: 'auth-district.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2frw9PDxjei46pOJgBXena4Z60J9totc',
    appId: '1:272011887725:ios:1bc380113492ea0756eb64',
    messagingSenderId: '272011887725',
    projectId: 'auth-district',
    storageBucket: 'auth-district.firebasestorage.app',
    iosBundleId: 'com.example.brlTask4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2frw9PDxjei46pOJgBXena4Z60J9totc',
    appId: '1:272011887725:ios:1bc380113492ea0756eb64',
    messagingSenderId: '272011887725',
    projectId: 'auth-district',
    storageBucket: 'auth-district.firebasestorage.app',
    iosBundleId: 'com.example.brlTask4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb3CFpHaRuD4kQ7Q02i0hWrFQSqwAB-aA',
    appId: '1:272011887725:web:c2eac4b6b16d396b56eb64',
    messagingSenderId: '272011887725',
    projectId: 'auth-district',
    authDomain: 'auth-district.firebaseapp.com',
    storageBucket: 'auth-district.firebasestorage.app',
    measurementId: 'G-6VV5EQB72K',
  );
}
