final List<Map<String, dynamic>> sampleDining = [
  {
    'id': 'dining_001',
    'name': 'Masala Synergy',
    'image': 'assets/images/masala-synergy.jpeg',
    'gallery': [
      'assets/images/dining/masala_gallery_1.jpg',
      'assets/images/dining/masala_gallery_2.jpg',
      'assets/images/dining/masala_gallery_3.jpg',
    ],
    'rating': 4.5,
    'totalRatings': 620,
    'cuisine': 'North Indian, Continental, Chinese',
    'location': 'Logix Mall International Center, Sector 32, Delhi NCR',
    'timings': 'Open • 12:00 PM to 11:30 PM',
    'distance': '3.5 km',
    'priceForTwo': '₹1,200',
    'whatsGoodHere': 'Butter Chicken, Dal Makhani, Paneer Tikka, Biryani',
    'offers': [
      {
        'title': 'CARNIVAL',
        'description': 'Pay bill to unlock the first reward',
        'icon': 'carnival',
      },
      {
        'title': 'FLAT 30% OFF',
        'validFrom': 'From 1:45 PM, today',
        'details': 'Valid on food bill above ₹1,000',
        'buttonText': 'Book now',
      },
      {
        'title': 'Flat 10% OFF up to ₹150',
        'details': 'ZOMATO30FF',
      },
    ],
    'menuUpdated': 'Updated 3 weeks ago',
    'description':
        'Masala Synergy offers an exquisite blend of traditional Indian flavors with a modern twist. Our chefs use authentic spices and fresh ingredients to create memorable dining experiences.',
    'highlights': [
      'Live Music',
      'Outdoor Seating',
      'Pet-Friendly',
      'Valet Parking',
      'Full Bar Available',
    ],
  },
  {
    'id': 'dining_002',
    'name': 'Bold Flavours',
    'image': 'assets/images/bold-flavor.jpg',
    'gallery': [
      'assets/images/dining/bold_gallery_1.jpg',
      'assets/images/dining/bold_gallery_2.jpg',
    ],
    'rating': 4.3,
    'totalRatings': 450,
    'cuisine': 'Italian, Mediterranean',
    'location': 'Cyber Hub, Gurugram',
    'timings': 'Open • 11:00 AM to 11:00 PM',
    'distance': '5.2 km',
    'priceForTwo': '₹1,500',
    'whatsGoodHere': 'Wood-fired Pizza, Pasta Carbonara, Tiramisu',
    'offers': [
      {
        'title': 'FLAT 25% OFF',
        'validFrom': 'All day',
        'details': 'Valid on food bill',
        'buttonText': 'Book now',
      },
    ],
    'menuUpdated': 'Updated 1 week ago',
    'description':
        'Experience authentic Italian cuisine in a cozy Mediterranean ambiance. Fresh ingredients, traditional recipes, and warm hospitality.',
    'highlights': [
      'Romantic Setting',
      'Wine Collection',
      'Private Dining',
    ],
  },
  {
    'id': 'dining_003',
    'name': 'Spice Route',
    'image': 'assets/images/spice-route.jpeg',
    'gallery': [
      'assets/images/dining/spice_gallery_1.jpg',
    ],
    'rating': 4.7,
    'totalRatings': 890,
    'cuisine': 'South Indian, Kerala Cuisine',
    'location': 'Connaught Place, Delhi',
    'timings': 'Open • 12:00 PM to 10:30 PM',
    'distance': '2.8 km',
    'priceForTwo': '₹900',
    'whatsGoodHere': 'Dosa, Appam, Kerala Fish Curry, Coconut Chutney',
    'offers': [
      {
        'title': 'FLAT 20% OFF',
        'validFrom': 'Lunch hours',
        'details': 'Valid till 4 PM',
        'buttonText': 'Book now',
      },
    ],
    'menuUpdated': 'Updated 5 days ago',
    'description':
        'A journey through the flavors of South India. Authentic recipes passed down through generations.',
    'highlights': [
      'Authentic Recipes',
      'Family-Friendly',
      'Lunch Buffet',
    ],
  },
  {
    'id': 'dining_004',
    'name': 'The Burger Hub',
    'image': 'assets/images/burger_hub.jpg',
    'gallery': [
      'assets/images/dining/burger_gallery_1.jpg',
      'assets/images/dining/burger_gallery_2.jpg',
    ],
    'rating': 4.2,
    'totalRatings': 320,
    'cuisine': 'American, Fast Food, Burgers',
    'location': 'Sector 18, Noida',
    'timings': 'Open • 11:00 AM to 11:30 PM',
    'distance': '4.1 km',
    'priceForTwo': '₹600',
    'whatsGoodHere': 'Cheese Burst Burger, Loaded Fries, Milkshakes',
    'offers': [
      {
        'title': 'BUY 1 GET 1',
        'validFrom': 'Today only',
        'details': 'On all burgers',
        'buttonText': 'Order now',
      },
    ],
    'menuUpdated': 'Updated 2 days ago',
    'description':
        'Juicy burgers, crispy fries, and creamy shakes. Perfect spot for casual dining with friends and family.',
    'highlights': [
      'Quick Service',
      'Delivery Available',
      'Budget-Friendly',
    ],
  },
  {
    'id': 'dining_005',
    'name': 'Sushi Palace',
    'image': 'assets/images/sushi_palace.jpg',
    'gallery': [
      'assets/images/dining/sushi_gallery_1.jpg',
      'assets/images/dining/sushi_gallery_2.jpg',
      'assets/images/dining/sushi_gallery_3.jpg',
    ],
    'rating': 4.6,
    'totalRatings': 540,
    'cuisine': 'Japanese, Asian Fusion',
    'location': 'DLF Mall of India, Noida',
    'timings': 'Open • 12:00 PM to 11:00 PM',
    'distance': '6.0 km',
    'priceForTwo': '₹2,000',
    'whatsGoodHere': 'California Roll, Salmon Nigiri, Tempura, Ramen',
    'offers': [
      {
        'title': 'FLAT 15% OFF',
        'validFrom': 'All day',
        'details': 'On bill above ₹1,500',
        'buttonText': 'Reserve table',
      },
    ],
    'menuUpdated': 'Updated 1 week ago',
    'description':
        'Authentic Japanese cuisine with a modern twist. Fresh ingredients flown in daily for the perfect sushi experience.',
    'highlights': [
      'Fresh Sushi Bar',
      'Sake Collection',
      'Teppanyaki Counter',
      'Private Rooms',
    ],
  },
];